### ISSUE TITLE
Set up git subtree

### ISSUE THREAD

**Issue by duoagencynyc** [Kazuki-tam/shopify-quick-theme#18]
Hi,

This starter theme is amazing! You are one of only a few that have actually taken the time to create something that is up to date and works correctly. Thank you and congratulations!

I'm having issues with adding my cloned repo using the Shopify GitHub integration. I saw on another website that you put this starter theme on that you mentioned something about 'git subtree's. I was wondering if you might be able to tell me how  I would go about setting this up correctly.

Your help would be greatly appreciated.

Thanks

**Comment by Kazuki-tam** [comment]
@duoagencynyc 
Sorry for the late reply.

This starter kit doesn't support the Shopify GitHub integration because Shopify allows only branches that match the default Shopify theme folder structure.
https://shopify.dev/themes/best-practices/version-control#separate-source-code-and-compiled-code-using-branches-recommended

You need to use git subtree if you want to use the Shopify GitHub integration.
https://www.atlassian.com/git/tutorials/git-subtree

However, it is harder than a normal operation to use git subtree, so I am considering if I create a new branch that enables GitHub integration as the default.

**Comment by Kazuki-tam** [comment]
I've created a new repository for Shopify GitHub integration.
https://github.com/Kazuki-tam/shopify-quick-theme-mix

**Comment by duoagencynyc** [comment]
Hi, @Kazuki-tam your new repository has worked perfectly. Thanks so much for taking the time to set it all up. Greatly apprecaited.
